### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by pandamako** [harada4atsushi/rails-open-rspec#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [rails-open-rspec](https://github.com/harada4atsushi/rails-open-rspec) package, v0.1.4
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/user/.atom/packages/rails-open-rspec/lib/rails-open-rspec.coffee:17

TypeError: Cannot read property 'getPath' of undefined
  at Object.module.exports.openSpec (/Users/user/.atom/packages/rails-open-rspec/lib/rails-open-rspec.coffee:17:29)
  at atom-workspace.<anonymous> (/Users/user/.atom/packages/rails-open-rspec/lib/rails-open-rspec.coffee:11:81)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/user/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Users/user/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/user/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/user/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/user/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -6:50.1.0 core:close (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:10.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:03.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.1.0 rails-open-rspec:open-rspec-file (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-rspec, v0.3.0
rails-open-rspec, v0.1.4
ruby-slim, v0.2.0
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by sasikumar87** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.3
**Thrown From**: [rails-open-rspec](https://github.com/harada4atsushi/rails-open-rspec) package, v0.1.8

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/WeLab/.atom/packages/rails-open-rspec/lib/rails-open-rspec.coffee:22

TypeError: Cannot read property 'getPath' of undefined
    at Object.module.exports.openSpec (/Users/WeLab/.atom/packages/rails-open-rspec/lib/rails-open-rspec.coffee:22:23)
    at atom-workspace.<anonymous> (/Users/WeLab/.atom/packages/rails-open-rspec/lib/rails-open-rspec.coffee:18:81)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
     -1:05.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:43.5.0 core:copy (atom-text-editor.editor.is-focused)
     -0:43.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:42.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:41.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:40.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:40.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.9.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:34.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:28.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:28.5.0 core:select-left (atom-text-editor.editor.is-focused)
  2x -0:27.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:17 core:save (atom-text-editor.editor.is-focused)
     -0:02.9.0 rails-open-rspec:open-rspec-file (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "rails-rspec",
      "rails-rspec"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
autocomplete-emojis, v2.2.2
language-elixir, v0.5.2
language-haml, v0.21.0
language-rspec, v0.3.0
linter-rubocop, v0.3.4
rails-open-rspec, v0.1.8
rspec, v0.3.2
rspec-snippets, v0.4.0

# Dev
No dev packages
```
